### ISSUE TITLE
Sublime text syntax highlighting

### ISSUE THREAD

**Issue by actuallymentor** [pugjs/babel-plugin-transform-react-pug#67]
Hello!

Thank you for this wonderful plugin.

Do you know how to get Sublime Text to syntax highlight `pug'...` template literals?

**Comment by ezhlobo** [comment]
@actuallymentor cool, I believe that the idea will be as simple as for Atom, but will try to help you with that soon.

**Comment by ezhlobo** [comment]
@actuallymentor I had a chance to make small research. Here is what I found: to get correct syntax highlighting for Flow (and maybe more things) there is a plugin [borela/naomi](https://github.com/borela/naomi).

To get syntax highlighting for pug in js we can create own syntax there and inherit existed one:
— Example: https://gist.github.com/subhaze/a754c8d17906f2a25ce2
— Documentation: http://www.sublimetext.com/docs/3/syntax.html

**Comment by actuallymentor** [comment]
Thank you for helping out so quickly!

I've read the documentation, but I don't fully understand it yet, could you elaborate on:

- What you mean by 'Flow'?
- In the .sublime-syntax:
-- How does one set the 'parent' highlight? I want to use Babel + this custom template literal
-- How does one include pug into the template literal scope? With the gist you link I am managing to make the literal highlight html (probably because of `include: 'scope:text.html.basic'`) but I have no idea what the scope name of other syntaxes is supposed to be

**Comment by actuallymentor** [comment]
So I figured out how to make the literal understand pug:

```yaml
%YAML 1.2
---
# See http://www.sublimetext.com/docs/3/syntax.html
name: Js with Template Literals
file_extensions:
  - js
scope: source.js.literal
contexts:
  main:
    - match: ""
      push: scope:source.js
      with_prototype:
      - match: 'pug`' <-- this matched a literal only if it is prepended by pug
        push:
          - meta_content_scope: text.html.basic.embedded.js
          - include: 'scope:text.pug' <-- This sets the highlighting ro pug
          - match: '`'
            pop: true
```

I still don't really understand how to involve babel in all of this...
